version: 0.2

runtime-versions:
  nodejs: 16

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run export
      - aws s3 sync ./out s3://juno-resume --delete
      - aws cloudfront create-invalidation --distribution-id E28MO0HY7W3BK5 --paths "/*"
